### ISSUE TITLE
Cosmic Text Editor Neovim Client Support

### ISSUE THREAD

**Issue by no-more-secrets** [pop-os/cosmic-edit#1]
Hi there,

As vim is one of the more populator text editors on Linux, it seems desirable to add a "vim mode" to the text editor.  In days past this would have consisted in implementing a small subset of vim keybindings into the text editor manually.  Nowadays, however, this task of integrating vim can be done in a much more effective and simpler way.  Neovim, which is vim's modern replacement, is designed with a client/server architecture.  So you can add a thin Neovim client into the Cosmic Text Editor that talks to the real Neovim backend (server) thereby providing a full authentic vim experience (all the keybindings, loading of .vimrc files, customizations, etc.).  For example, you could google "Neovim frontend" to see other GUI frontends to neovim that people have created.

If the Cosmic Text Editor could be given a builtin Neovim client then it could function as a drop-in replacement for any user's full Neovim setup with little effort on either the part of System76 or on the user.

**Comment by jacobmealey** [comment]
I don't speak for the development team, but it seems like there is already [Vi mode in cosmic-text](https://github.com/pop-os/cosmic-text/blob/main/src/edit/vi.rs), and [in main](https://github.com/pop-os/cosmic-text-editor/blob/aed6b9b0c8e2a55341b226e6a1e7ffc5a458a46f/src/main.rs#L69) it looks like there may be a way to directly enable vi editor (not sure if it would be at compile time or runtime but :shrug:).

I know this isn't exactly what you are describing but it seems pretty close.

**Comment by no-more-secrets** [comment]
The "Vi mode" that you linked is exactly what I think they should avoid -- namely, manually implementing Vi commands to simulate it, which is what they are doing:

https://github.com/pop-os/cosmic-text/blob/main/src/edit/vi.rs#L87

There is a pretty big difference between doing that and integrating a Neovim client in that by merely simulating it you are only getting a very small subset of vim functionality, it it likely won't respect you personal .vimrc config.

**Comment by ad-laurentius** [comment]
Not that I have any authority to tell you guys what to do, it's your editor after all, but I wanted to say that agree with @no-more-secrets . If you want a proper vi/m mode, with all the goodness that comes with it (including plugins, ability to configure and personalise...) the way to go is integrating a Neovim client. VSCode has it. It would even mean less work, as you could take advantage of all the development taking place in Neovim without having to re-invent the wheel.

**Comment by jackpot51** [comment]
The concept of this program is to provide a pure rust, GUI-based editor that has optional vim-like keybindings, not to fully replicate the functionality of neovim. If you want neovim, I would recommend to use neovim.
