### ISSUE TITLE
Undo/redo not always putting text back in the same place

### ISSUE THREAD

**Issue by jackpot51** [pop-os/cosmic-edit#102]
Some changes must be missing from history because undo/redo does not always restore the file as expected.

**Comment by Dygear** [comment]
If you Ctrl+A the file, then delete it with the space bar, then undo it simply looks like the new lines are stripped. That seems to be the problem. Newlines are not preserved in the undo / redo buffer.

**Comment by jackpot51** [comment]
Indeed, that is the main issue

**Comment by jackpot51** [comment]
Hopefully fixed by 2e5cedb
