### ISSUE TITLE
Project panel: Filenames start getting cut off early after ~4ish levels of nested directories

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-edit#151]
![screenshot-2024-03-06-18-34-52](https://github.com/pop-os/cosmic-edit/assets/13512097/b3d1e81c-b3cb-4d51-ba7f-1915b2019405)

**Comment by mmstick** [comment]
This is a bug in libcosmic with calculating the layout bounds for indented buttons.

**Comment by jackpot51** [comment]
@mmstick can you work on a fix?

**Comment by mmstick** [comment]
Yes

**Comment by mmstick** [comment]
Fixed by https://github.com/pop-os/libcosmic/pull/330
