### ISSUE TITLE
Opening a project through the file menu doesn't open file-viewer.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-edit#156]
This seems unintuitive to me, as a new user might not know to open the project view independently of opening a project through the file menu. We should have the file viewer pop open whenever the first project is opened. Potentially, we can have a toggle in settings so that, as users gain familiarity with Edit, they can turn the feature off.

**Comment by leviport** [comment]
Also applies to Ctrl + Shift + O. I can hit that hotkey, open a folder, and have no visual indication that anything happened. Then I can open the project pane, where I see that the folder I just opened was opened as expected.
