### ISSUE TITLE
No prompt to save changes when closing application.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-edit#169]
This might be dependent on other outstanding work, but at current (https://github.com/pop-os/cosmic-edit/commit/3d4fa8475993fd4838d1090006e75d141efc2470), there is no form of dialogue or prevention to stop cosmic-editor from being closed while unsaved changes are present in documents. This is true when closing using the button in the upper-right, by quitting from the `file` menu, or if using the close button on the application tab when using stacked windows.

**Comment by WatchMkr** [comment]
It does work if trying to close a tab with a modified document.
