### ISSUE TITLE
Pressing Enter with Find box focused sometimes results in inserting a newline

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-edit#172]
Version: cd1b322

When typing text into the Find text box and pressing Enter, the behavior is inconsistent:

- Sometimes, the cursor goes to a match, or stays where it's at (which is the expected behavior)
- Sometimes, that works, but I also get a newline inserted where my cursor was before
- Sometimes, I just get a newline inserted, and find doesn't actually work

**Comment by WatchMkr** [comment]
Seems related to https://github.com/pop-os/cosmic-edit/issues/185
