### ISSUE TITLE
Git clone/build error

### ISSUE THREAD

**Issue by ItMeCorban** [pop-os/cosmic-edit#181]
Installing `cosmic-epoch-git` from the AUR or the standalone `cosmic-edit-git` I get the below error. The screenshot file does get downloaded during the clone process but by the time I get the error, the file is gone. 

I understand this is pre-alpha so not a high priority, just thought I'd make note in case this becomes an issue

```
Cloning into 'cosmic-edit'...
done.
Downloading res/screenshots/screenshot-1.png (259 KB)
Error downloading object: res/screenshots/screenshot-1.png (3ba78b1): Smudge error: Error downloading res/screenshots/screenshot-1.png (3ba78b19f6c4ecce1cbbb7a85495426ab5102575fef9838b5a1df199c951e985): error transferring "3ba78b19f6c4ecce1cbbb7a85495426ab5102575fef9838b5a1df199c951e985": [0] remote missing object 3ba78b19f6c4ecce1cbbb7a85495426ab5102575fef9838b5a1df199c951e985

Errors logged to '/home/ItMeCorban/.cache/yay/cosmic-epoch-git/src/cosmic-edit/.git/lfs/logs/20240430T105121.374869372.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: res/screenshots/screenshot-1.png: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

==> ERROR: Failure while creating working copy of cosmic-edit git repo
    Aborting...
 -> error making: cosmic-epoch-git-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
cosmic-epoch-git - exit status 1
```

**Comment by joshuamegnauth54** [comment]
Are you able to clone and compile this repo (i.e. not from AUR)? Compiling from main on Arch works for me by directly using this repo.

According to comments from the [AUR page](https://aur.archlinux.org/packages/cosmic-edit-git), it should work if you disable `git-lfs`.

**Comment by mmstick** [comment]
Arch-specific issue. Should ask Arch maintainers for help.

**Comment by ItMeCorban** [comment]
> Are you able to clone and compile this repo (i.e. not from AUR)? Compiling from main on Arch works for me by directly using this repo.
> 
> According to comments from the [AUR page](https://aur.archlinux.org/packages/cosmic-edit-git), it should work if you disable `git-lfs`.

Hmm that's interesting, I installed git-lfs after my initial install failed because it was missing.

I'll try clone and compile direct from the repo, thanks :)

**Comment by Quackdoc** [comment]
@ItMeCorban arch makepkg doesn't support lfs I've raised as similar issue here https://github.com/pop-os/cosmic-greeter/issues/5 but you can see a fix here https://github.com/Quackdoc/pkgbuild-scripts/blob/Master/cosmic-epoch/cosmic-greeter-git/PKGBUILD

also a relatively new issue came up, https://github.com/git-lfs/git-lfs/issues/5749 breaks a lot of packages by default as this now needs to be exported. `GIT_CLONE_PROTECTION_ACTIVE=false`

Ideally git-lfs would be avoided since IMO it's more headaches then it's worth and it's not really a true given it will always be supported (IE. Arch) but this is a viable workaround
