### ISSUE TITLE
Text input field doesn't lose focus when clicking a button in the Find menu

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-edit#185]
When the Find menu first opens, the main text input field loses focus, but when reselecting the input field with the Find menu still open, and then clicking on the search bar in the menu, typing in the search bar also inputs text to the file.
If something is highlighted in the file, and there's something in the Find search bar, clicking on arrows after the main text input was selected results in a similar behavior to Shift + Click from the highlighted item to the Find result.
Might be related to #172.

https://github.com/pop-os/cosmic-edit/assets/150025636/40474cad-c9af-4ce2-b8eb-a8528f7fcf9e

Unrelated, the clear text button in the search bar doesn't work.

**Comment by jacobgkau** [comment]
Confirmed, this is still happening.

**Comment by git-f0x** [comment]
This is likely fixed, so I'll close this.
