### ISSUE TITLE
[Feature Request] "Cancel" option when closing window & unsaved changes window appears

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-edit#189]
Would be cool, if one could press on cancel when the unsaved changes window appears, causing the unsaved changes window to close while letting the editor & its current content stay open.

**Comment by WatchMkr** [comment]
@jackpot51 @maria-komarova I propose we add the Cancel text button to the current dialog for the alpha and decide whether we implement the discussed design for alpha 2 or leave as is.
