### ISSUE TITLE
feat: Add hard tab support

### ISSUE THREAD

**Issue by RachaelAva1024** [pop-os/cosmic-edit#201]
I love using COSMIC Edit, but there's one feature that's been keeping me from using it regularly: hard tabs.

I prefer hard tabs because it usually means less mashing of the arrow keys to move the text cursor around. Currently, hard tabs are rendered as circles, (See screenshot below) but I would really like to see hard tab support added in the near future.

![Hard tabs are better IMHO](https://github.com/pop-os/cosmic-edit/assets/83562876/df28f985-78d5-4d18-ad24-488f37f61ce5)
(Rust file created and edited with nano being opened in COSMIC Edit)

**Comment by leviport** [comment]
Tabs being rendered as circles/ovals is being tracked in https://github.com/pop-os/cosmic-text/issues/248

**Comment by RachaelAva1024** [comment]
> Tabs being rendered as circles/ovals is being tracked in [pop-os/cosmic-text#248](https://github.com/pop-os/cosmic-text/issues/248)

My apologies! I should have checked cosmic-text too.

**Comment by jackpot51** [comment]
Closing to track on cosmic-text. What font is this?

**Comment by RachaelAva1024** [comment]
> Closing to track on cosmic-text. What font is this?

Terminess Nerd Font Mono. I love this font, but last I checked, COSMIC Term can't use that font, which sucks because I REALLY like that font for a terminal. I use it on Alacritty, but can't with COSMIC Term.

**Comment by jackpot51** [comment]
Please open a new issue if this is for cosmic-term. The only fonts listed are ones that identify themselves as monospace. I can check the font you mentioned to see if it is being filtered out for some reason.
