### ISSUE TITLE
Hard freeze on paste to find/search

### ISSUE THREAD

**Issue by flukejones** [pop-os/cosmic-edit#202]
I can cause this consistently:

1. Open a doc of any sort
2. Select some text in it
3. Ctrl+c, ctrl+f, ctrl+v
4. ...
5. profit?

On pasting to the search it freezes completely and has to be killed. It also appears to be just ctrl+v in the search in general.

Using latest commit as of today.

**Comment by WatchMkr** [comment]
I'm unable to reproduce this now. Are you still seeing this issue?

**Comment by flukejones** [comment]
Yes I can still reproduce.

**Comment by jackpot51** [comment]
Can you get the version of cosmic-edit from the View->About  COSMIC Text Editor... menu item?

**Comment by flukejones** [comment]
I'm so sorry y'all. I had a copy in `~/.local/bin/` for some reason. Removing this and ensuring I'm actually using the latest version, looks like all is good.
