### ISSUE TITLE
[INCONSISTENCY] COSMIC text doesn't zoom with ctrl + plus; while COSMIC terminal does.

### ISSUE THREAD

**Issue by feikedonia** [pop-os/cosmic-edit#279]
In Cosmic Terminal, I can Ctrl + plus to zoom in and make the text bigger, I expected this functionality as well in Cosmic Text editor.

With regards,

Feike

**Comment by leviport** [comment]
Duplicate of https://github.com/pop-os/cosmic-edit/issues/277
