### ISSUE TITLE
Change and add shortcuts

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-edit#38]
New file: Ctrl + T
New window: Ctrl + N
Close file (under open file): Ctrl + W
Open project (under close file): Ctrl+Shift+O

Change "Open recent >" to "Open recent file >"
Add "Open recent project >" underneath

**Comment by jackpot51** [comment]
I have updated the keybinds and added the project menu items. If you have edited settings it may have cached keybinds in `~/.config/cosmic/com.system76.CosmicEdit/v1/keybinds`, removing that file will load the defaults. I'll need a different format for saving them to ensure new defaults can be added.
