### ISSUE TITLE
Theme and Syntax highlighting adjustment

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-edit#39]
In the View menu
- [ ] Remove "View > Syntax highlighting..." 

In Settings
- [ ] Rename current "Theme" option to "Syntax highlighting"
- [ ] Add Theme above "Syntax highlighting". Theme is intended to be a system appearance override. Options in the dropdown should be "Match desktop" (default) "Light" and "Dark"

With syntax highlighting following light and dark modes, I think we can do something better to expose to the user that there are actually two settings. Perhaps "Syntax dark" and "Syntax light".

**Comment by jackpot51** [comment]
I believe View -> Syntax highlighting... is meant to be used for selecting a file type if not automatically detected (or if wrongly detected)

**Comment by jackpot51** [comment]
This change was done in 7170e64f4ad700fa724644bbdbf2278f23845a19
