### ISSUE TITLE
Can't build.

### ISSUE THREAD

**Issue by jrapf32** [pop-os/cosmic-edit#43]
error[E0599]: no method named `drain_filter` found for struct `Vec<CommandItem<T>>` in the current scope
file: index.crates.io-6f17d22bba15001f/undo_2-0.2.0/src/lib.rs:1175:31
     |
1175 |                 self.commands.drain_filter(|_| {
     |                 --------------^^^^^^^^^^^^ method not found in `Vec<CommandItem<T>>`

**Comment by jackpot51** [comment]
What version of Rust are you trying to build with?

**Comment by jrapf32** [comment]
rustc 1.72.0-nightly (36fb58e43 2023-06-26).

**Comment by jrapf32** [comment]
Rustup was being weird.
