### ISSUE TITLE
Scrollbar doesn't reflect actual length of file

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-edit#47]
The scrollbar initially shows a single pixel row at the top; I'm not sure if that's expected or not.

When adding a second line to the file, the scrollbar appears as if the file is only halfway in view. It can't actually be moved/scrolled because the file isn't actually that long.

The scrollbar doesn't begin behaving somewhat as expected until the file is actually scrollable, although the scrollbar never reaches the bottom of the page.

https://github.com/pop-os/cosmic-edit/assets/7199422/e248b444-1410-4414-9bb7-22aa7ff39048

**Comment by jackpot51** [comment]
Should be fixed by 125483c
