### ISSUE TITLE
Settings headers have excessive vertical padding

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-edit#49]
- Appearance:

![Screenshot from 2023-11-15 16-29-39](https://github.com/pop-os/cosmic-edit/assets/7199422/98ebb1cb-1f79-43f1-9569-da8bde6e2cea)

- Keyboard shortcuts:

![Screenshot from 2023-11-15 16-30-17](https://github.com/pop-os/cosmic-edit/assets/7199422/10564e29-d766-4f9f-8b56-9a98dbe24500)

**Comment by jackpot51** [comment]
@mmstick could you look into this? I don't see a reason why this is happening. All the code is in the context_drawer function in src/main.rs

**Comment by mmstick** [comment]
Sure

**Comment by jackpot51** [comment]
This is caused by the wgpu renderer. I'm not sure why it behaves differently. I've switched back to softbuffer in the meantime

**Comment by jackpot51** [comment]
I've re-enabled wgpu, keep an eye out for this bug.
