### ISSUE TITLE
After changing snytax color scheme and closing settings pane, text area temporarily goes blank

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-edit#50]
More specifically, the text area turns into a solid color until the text is interacted with. Typing any text fixes it immediately; clicking somewhere the cursor already was (e.g. past the end of a line) doesn't fix it, but clicking in a way that moves the input cursor does fix it.

https://github.com/pop-os/cosmic-edit/assets/7199422/8b92331e-1fc0-43fd-8b76-80bf43c5ff58

**Comment by leviport** [comment]
Looks very similar to the behavior in https://github.com/pop-os/cosmic-edit/issues/9

**Comment by jacobgkau** [comment]
Oh, this is a duplicate.
