### ISSUE TITLE
No horizontal scrolling (text gets cut off when wrapping is disabled)

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-edit#59]
**Version:** 8996394

**Issue description:** When the length of a line of text extends beyond the size of the window and text wrapping is disabled, the text is simply cut off. The cursor can be moved past the end of the window with the keyboard, and the non-visible text can be modified, but the view can't be scrolled so the end of the text is visible.

**Expected behavior:** The view should be horizontally scrollable when text wrapping is disabled and the text extends past the edge of the window. Moving the cursor (or typing anything) past the edge of the window should scroll automatically so the cursor remains visible. Ideally, a horizontal scrollbar should be visible to indicate when the view is scrollable.

**Example:**

https://github.com/pop-os/cosmic-edit/assets/7199422/b59ea767-96b9-486f-a6db-3dd1f54b6a7d

**Comment by Dygear** [comment]
I gave this a shot last night. Getting a horizontal scroll bar to work is going to take more brain power from me. I need to spend a lot more time learning the render surfaces of this system before I give this another go. This is for sure a high priority tho.
