### ISSUE TITLE
No confirmation when exiting with unsaved changes

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-edit#60]
Some kind of dialog asking if the user wants to save & quit or quit without saving should probably be added. Currently, the app just closes, discarding unsaved changes:

https://github.com/pop-os/cosmic-edit/assets/7199422/5b2945f5-759c-4437-aa90-9fd1f39d1f67

#### New file:

![image](https://github.com/pop-os/cosmic-edit/assets/7199422/f2c734d8-e86f-49c9-96ca-13dd06cba630)

#### Existing file:

![image](https://github.com/pop-os/cosmic-edit/assets/7199422/09fc4efe-70cf-4706-910e-d0dc85364534)

#### New file:

![image](https://github.com/pop-os/cosmic-edit/assets/7199422/60fba83c-0d00-4bfc-a5e6-6eabe306908f)

#### Existing file:

![image](https://github.com/pop-os/cosmic-edit/assets/7199422/eef2d7ad-c56a-4d56-9df3-5bd29de44dff)

**Comment by Dygear** [comment]
Well, the good news is that there is a dirty bit set somewhere already. When you edit a file in a tab, a little circle shows up next to the name of the file denoting its changed state. Now it's just a matter of taking that information and handling it when the Message::Close is passed.

**Comment by WatchMkr** [comment]
COSMIC dialog design is here: https://www.figma.com/file/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?node-id=8235%3A11383&mode=dev

Primary: Save
Secondary: Cancel
Tertiary: Close without saving

**Comment by RefinedSoftwareLLC** [comment]
Please see related: [Backup Unsaved Changes #94](https://github.com/pop-os/cosmic-edit/issues/94#issue-2080385765)
