### ISSUE TITLE
Capturing Enter keypresses coming off of other apps' focus

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-edit#65]
When using COSMIC Edit on GNOME, if I take these steps:

1. Have COSMIC Edit focused
2. Open the Launcher, search for some other app (e.g. calculator), and open it with Enter

COSMIC Edit receives the Enter keypress and adds a line break before my focus is switched to the Calculator. Gedit and KWrite don't do this. I'd expect the Launcher to be the only thing to receive that Enter keypress since it's what's focused at the time of pressing the key.

This also happens if I focus COSMIC Edit, lock the GNOME session, and go to unlock it (typing the password and pressing Enter). Interestingly, if I enter a wrong password, COSMIC Edit still receives the Enter keypress-- I can enter an incorrect password multiple times (pressing Enter after each one) and then observe multiple line breaks in COSMIC Edit after successfully unlocking the session.

**Comment by Dygear** [comment]
Woah, that's an interesting bug report. The enter keypress propagating past the login screen even after a failed login attempt is ... concerning.

**Comment by XV-02** [comment]
@jacobgkau It looks like this might be fixed from testing on one of the lab units. As you know what you're looking for could you double check whether this is resolved now?

**Comment by jacobgkau** [comment]
Yes, I'm no longer seeing this happening.
