### ISSUE TITLE
MSRV & Style Guide

### ISSUE THREAD

**Issue by Dygear** [pop-os/cosmic-edit#78]
Is there an already accepted MSRV and style guide for any of the Cosmic crates? I was compiling this on my MacBook and two general errors popped out with the regular debug build. With Clippy lints enabled, many more come to the surface. Are these things that should be fixed?

src/textbox:rs 121:123
```RUST
    if alpha == 0 {
        // Do not draw if alpha is zero
        return;
    } else if alpha >= 255 {
```

This is currently an unneeded `return` but could be an important placement in later versions should the if structure change later on.

src/textbox.rs 175
```RUST
impl<'a, 'editor, Message, Renderer> Widget<Message, Renderer> for TextBox<'a, Message>
```

The `'editor` lifetime isn't used in the impl at this time. Should this be removed?

src/textbox.rs 236:239
```RUST
        match &state.dragging {
            Some(Dragging::Scrollbar { .. }) => return mouse::Interaction::Idle,
            _ => {}
        }
```

This could be a `let if statement` as it really only has a single match.

src/textbox.rs 511
```RUST
        let image_position = layout.position() + [self.padding.left as f32, self.padding.top as f32].into();
```

`self.padding.left` and `self.padding.top` is already f32. I assume this was a left over from a pervious version that was an `i32` or `u32`? But the conversion here is now not needed.

src/textbox.rs 807
```RUST
impl<'a, 'editor, Message, Renderer> From<TextBox<'a, Message>> for Element<'a, Message, Renderer>
```

The `'editor` lifetime is not used in this impl at all and can be removed.

---

I ask about all of these things, as I want to make sure I'm not tripping over a style guide for these family of crates. I also want to point out that I'm only the textbox file as an example not to pick on anyone. This file was just as an area where clippy had some varied examples in its list. I'm extremely impressed with the work here and would love to help, in any way that I can.

**Comment by jackpot51** [comment]
All of these should be fine to fix, thanks

**Comment by jackpot51** [comment]
MSRV can be set to 1.70

**Comment by Dygear** [comment]
So the style guide is "Make Clippy Happy." and the MSRV is 1.70. PR submitted with changes. Closing.
