### ISSUE TITLE
Text area goes away when closing settings pane with the mouse

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-edit#9]
To recreate:
- Have a document open with some text in it
- Open View > Settings pane (or with ctrl + comma hotkey)
- Click the "Close >" button in the Settings pane
- The document vanishes. It looks like the lighter rectangle behind it might be popping up in front of it. Clicking the document area makes it re-appear.

https://github.com/pop-os/cosmic-edit/assets/13512097/b7bbd238-714e-4627-bda0-d5da9a82b862

Closing the Settings pane with Ctrl + comma does not make the document vanish, but a comma is inserted into the document upon closing the pane. The comma probably shouldn't be added to the document when using that hotkey to close the Settings pane.

**Comment by jackpot51** [comment]
There appears to be a libcosmic bug where the modifiers sent to the text box are updated after the comma is sent, causing the comma to be inserted.

**Comment by jackpot51** [comment]
Fixed by https://github.com/pop-os/cosmic-edit/commit/3fc8a76509faf5fa6a74254a4a6c8320b2209371
