### ISSUE TITLE
Crashes after suspend/resume

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-edit#91]
Same issue as https://github.com/pop-os/cosmic-term/issues/12. If I have COSMIC Text open and I suspend/resume, then it's no longer open. I see the following in the logs:

```
Dec 27 15:32:22 serw13 com.system76.CosmicEdit.desktop[16264]: thread 'main' panicked at /build/cosmic-edit-DLyCcn/cosmic-edit-0.1.0~1703632828~22.04~cbb0f89/vendor/wgpu/src/backend/direct.rs:822:30:
Dec 27 15:32:22 serw13 com.system76.CosmicEdit.desktop[16264]: Error in Surface::get_current_texture_view: Validation Error
Dec 27 15:32:22 serw13 com.system76.CosmicEdit.desktop[16264]: Caused by:
Dec 27 15:32:22 serw13 com.system76.CosmicEdit.desktop[16264]:     Parent device is lost
Dec 27 15:32:22 serw13 com.system76.CosmicEdit.desktop[16264]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looks like some kind of wgpu issue.

**Comment by Dygear** [comment]
Just tested this on Pop!_OS 22.04 LTS, with the 6.6.6 kernel. Having Cosmic Text open with the main.rs file, I suspend my Galp 7, and then resumed. No instances of COSMIC Text crashed. I had no panics of any kind. Pending no response, this can probably be closed in 24 hours.

**Comment by Dygear** [comment]
@jackpot51 Yeah this can be closed. This no longer happens in the current builds.

**Comment by jacobgkau** [comment]
Confirmed this is no longer occurring as of f29b939.

> Pending no response, this can probably be closed in 24 hours.

@Dygear I'm a quality assurance engineer at System76, Jeremy can get a response out of me if he needs it. 😉 Thank you for your triage efforts, though.

**Comment by Dygear** [comment]
Oh hey, nice to meet you!
