### ISSUE TITLE
Typing when text is selected results in panic

### ISSUE THREAD

**Issue by holly-hacker** [pop-os/cosmic-edit#96]
`cosmic-edit` has some very weird behavior when using `ctrl+a` to select all text when ran under WSL, including panicking. I noticed this when trying out cosmic-edit under WSL in Windows, but it's possible this behavior also exists under native linux (which I'm unable to test right now).

## Test setup
I'm running Ubuntu 22.04 WSL and I get cosmic-edit using the nix package manager like so:
```sh
nix shell nixpkgs#cosmic-edit --command cosmic-edit
```

This pulls in version `unsable-2023-11-29`

## Repro

1. Open cosmic-edit
2. Type some text, such as `test`
3. Select all text using <kbd>ctrl</kbd>+<kbd>a</kbd>
4. Overwrite the selected text by typing at least 2 characters. Notice that the first character works correctly but the second will cause a panic.

This outputs the following console log (ERROR and WARN likely due to WSL):
```
$ nix shell nixpkgs#cosmic-edit --command cosmic-edit
[2024-01-13T23:01:00Z ERROR i18n_embed::requester] Unable to parse your locale: ParserError(InvalidLanguage)
[2024-01-13T23:01:00Z WARN  winit::platform_impl::platform::x11::util::randr] XRandR reported that the display's 0mm in size, which is certifiably insane
thread 'main' panicked at /build/rustc-1.74.0-src/library/alloc/src/string.rs:1641:9:
assertion failed: self.is_char_boundary(at)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

There are other similar cases involving typing with selected text that produce other strange behavior, but I assume they all have the same root cause. For example, the described panic occurs when text is selected and the cursor is at the start of the selection, but typing with the cursor at the end of the selection only results in only the last character being shown on screen.

**Comment by Dygear** [comment]
Can you confirm this is still a problem with the current build as of 7 hours ago? I just attempted the steps to reproduce this problem and it's working fine for me under native linux. (Pop!_OS 22.04  LTS with Linux 6.6.6)

**Comment by holly-hacker** [comment]
The latest version isn't in the nix package manager yet but I compared the latest master to `4a3dd101f35eb3c1c585f104d78ed4ee31d393d3` and it seems to be fixed now.
